"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class AgentActionProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VECTOR_ACTIONS_DEPRECATED_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    CONTINUOUS_ACTIONS_FIELD_NUMBER: builtins.int
    DISCRETE_ACTIONS_FIELD_NUMBER: builtins.int
    @property
    def vector_actions_deprecated(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """mark as deprecated in communicator v1.3.0"""
    value: builtins.float
    @property
    def continuous_actions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def discrete_actions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        vector_actions_deprecated: collections.abc.Iterable[builtins.float] | None = ...,
        value: builtins.float = ...,
        continuous_actions: collections.abc.Iterable[builtins.float] | None = ...,
        discrete_actions: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["continuous_actions", b"continuous_actions", "discrete_actions", b"discrete_actions", "value", b"value", "vector_actions_deprecated", b"vector_actions_deprecated"]) -> None: ...

global___AgentActionProto = AgentActionProto
