# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    NewType as typing___NewType,
    cast as typing___cast,
)


builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

CommandProtoValue = typing___NewType('CommandProtoValue', builtin___int)
type___CommandProtoValue = CommandProtoValue
CommandProto: _CommandProto
class _CommandProto(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[CommandProtoValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    STEP = typing___cast(CommandProtoValue, 0)
    RESET = typing___cast(CommandProtoValue, 1)
    QUIT = typing___cast(CommandProtoValue, 2)
STEP = typing___cast(CommandProtoValue, 0)
RESET = typing___cast(CommandProtoValue, 1)
QUIT = typing___cast(CommandProtoValue, 2)
type___CommandProto = CommandProto
