"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class DemonstrationMetaProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    API_VERSION_FIELD_NUMBER: builtins.int
    DEMONSTRATION_NAME_FIELD_NUMBER: builtins.int
    NUMBER_STEPS_FIELD_NUMBER: builtins.int
    NUMBER_EPISODES_FIELD_NUMBER: builtins.int
    MEAN_REWARD_FIELD_NUMBER: builtins.int
    api_version: builtins.int
    demonstration_name: builtins.str
    number_steps: builtins.int
    number_episodes: builtins.int
    mean_reward: builtins.float
    def __init__(
        self,
        *,
        api_version: builtins.int = ...,
        demonstration_name: builtins.str = ...,
        number_steps: builtins.int = ...,
        number_episodes: builtins.int = ...,
        mean_reward: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["api_version", b"api_version", "demonstration_name", b"demonstration_name", "mean_reward", b"mean_reward", "number_episodes", b"number_episodes", "number_steps", b"number_steps"]) -> None: ...

global___DemonstrationMetaProto = DemonstrationMetaProto
