"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TrainingEnvironmentInitialized(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MLAGENTS_VERSION_FIELD_NUMBER: builtins.int
    MLAGENTS_ENVS_VERSION_FIELD_NUMBER: builtins.int
    PYTHON_VERSION_FIELD_NUMBER: builtins.int
    TORCH_VERSION_FIELD_NUMBER: builtins.int
    TORCH_DEVICE_TYPE_FIELD_NUMBER: builtins.int
    NUM_ENVS_FIELD_NUMBER: builtins.int
    NUM_ENVIRONMENT_PARAMETERS_FIELD_NUMBER: builtins.int
    RUN_OPTIONS_FIELD_NUMBER: builtins.int
    mlagents_version: builtins.str
    mlagents_envs_version: builtins.str
    python_version: builtins.str
    torch_version: builtins.str
    torch_device_type: builtins.str
    num_envs: builtins.int
    num_environment_parameters: builtins.int
    run_options: builtins.str
    def __init__(
        self,
        *,
        mlagents_version: builtins.str = ...,
        mlagents_envs_version: builtins.str = ...,
        python_version: builtins.str = ...,
        torch_version: builtins.str = ...,
        torch_device_type: builtins.str = ...,
        num_envs: builtins.int = ...,
        num_environment_parameters: builtins.int = ...,
        run_options: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["mlagents_envs_version", b"mlagents_envs_version", "mlagents_version", b"mlagents_version", "num_environment_parameters", b"num_environment_parameters", "num_envs", b"num_envs", "python_version", b"python_version", "run_options", b"run_options", "torch_device_type", b"torch_device_type", "torch_version", b"torch_version"]) -> None: ...

global___TrainingEnvironmentInitialized = TrainingEnvironmentInitialized

@typing_extensions.final
class TrainingBehaviorInitialized(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BEHAVIOR_NAME_FIELD_NUMBER: builtins.int
    TRAINER_TYPE_FIELD_NUMBER: builtins.int
    EXTRINSIC_REWARD_ENABLED_FIELD_NUMBER: builtins.int
    GAIL_REWARD_ENABLED_FIELD_NUMBER: builtins.int
    CURIOSITY_REWARD_ENABLED_FIELD_NUMBER: builtins.int
    RND_REWARD_ENABLED_FIELD_NUMBER: builtins.int
    BEHAVIORAL_CLONING_ENABLED_FIELD_NUMBER: builtins.int
    RECURRENT_ENABLED_FIELD_NUMBER: builtins.int
    VISUAL_ENCODER_FIELD_NUMBER: builtins.int
    NUM_NETWORK_LAYERS_FIELD_NUMBER: builtins.int
    NUM_NETWORK_HIDDEN_UNITS_FIELD_NUMBER: builtins.int
    TRAINER_THREADED_FIELD_NUMBER: builtins.int
    SELF_PLAY_ENABLED_FIELD_NUMBER: builtins.int
    CURRICULUM_ENABLED_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    behavior_name: builtins.str
    trainer_type: builtins.str
    extrinsic_reward_enabled: builtins.bool
    gail_reward_enabled: builtins.bool
    curiosity_reward_enabled: builtins.bool
    rnd_reward_enabled: builtins.bool
    behavioral_cloning_enabled: builtins.bool
    recurrent_enabled: builtins.bool
    visual_encoder: builtins.str
    num_network_layers: builtins.int
    num_network_hidden_units: builtins.int
    trainer_threaded: builtins.bool
    self_play_enabled: builtins.bool
    curriculum_enabled: builtins.bool
    config: builtins.str
    def __init__(
        self,
        *,
        behavior_name: builtins.str = ...,
        trainer_type: builtins.str = ...,
        extrinsic_reward_enabled: builtins.bool = ...,
        gail_reward_enabled: builtins.bool = ...,
        curiosity_reward_enabled: builtins.bool = ...,
        rnd_reward_enabled: builtins.bool = ...,
        behavioral_cloning_enabled: builtins.bool = ...,
        recurrent_enabled: builtins.bool = ...,
        visual_encoder: builtins.str = ...,
        num_network_layers: builtins.int = ...,
        num_network_hidden_units: builtins.int = ...,
        trainer_threaded: builtins.bool = ...,
        self_play_enabled: builtins.bool = ...,
        curriculum_enabled: builtins.bool = ...,
        config: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["behavior_name", b"behavior_name", "behavioral_cloning_enabled", b"behavioral_cloning_enabled", "config", b"config", "curiosity_reward_enabled", b"curiosity_reward_enabled", "curriculum_enabled", b"curriculum_enabled", "extrinsic_reward_enabled", b"extrinsic_reward_enabled", "gail_reward_enabled", b"gail_reward_enabled", "num_network_hidden_units", b"num_network_hidden_units", "num_network_layers", b"num_network_layers", "recurrent_enabled", b"recurrent_enabled", "rnd_reward_enabled", b"rnd_reward_enabled", "self_play_enabled", b"self_play_enabled", "trainer_threaded", b"trainer_threaded", "trainer_type", b"trainer_type", "visual_encoder", b"visual_encoder"]) -> None: ...

global___TrainingBehaviorInitialized = TrainingBehaviorInitialized
