# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class TrainingEnvironmentInitialized(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    mlagents_version = ... # type: typing___Text
    mlagents_envs_version = ... # type: typing___Text
    python_version = ... # type: typing___Text
    torch_version = ... # type: typing___Text
    torch_device_type = ... # type: typing___Text
    num_envs = ... # type: builtin___int
    num_environment_parameters = ... # type: builtin___int
    run_options = ... # type: typing___Text

    def __init__(self,
        *,
        mlagents_version : typing___Optional[typing___Text] = None,
        mlagents_envs_version : typing___Optional[typing___Text] = None,
        python_version : typing___Optional[typing___Text] = None,
        torch_version : typing___Optional[typing___Text] = None,
        torch_device_type : typing___Optional[typing___Text] = None,
        num_envs : typing___Optional[builtin___int] = None,
        num_environment_parameters : typing___Optional[builtin___int] = None,
        run_options : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> TrainingEnvironmentInitialized: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"mlagents_envs_version",u"mlagents_version",u"num_environment_parameters",u"num_envs",u"python_version",u"run_options",u"torch_device_type",u"torch_version"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"mlagents_envs_version",b"mlagents_envs_version",u"mlagents_version",b"mlagents_version",u"num_environment_parameters",b"num_environment_parameters",u"num_envs",b"num_envs",u"python_version",b"python_version",u"run_options",b"run_options",u"torch_device_type",b"torch_device_type",u"torch_version",b"torch_version"]) -> None: ...

class TrainingBehaviorInitialized(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    behavior_name = ... # type: typing___Text
    trainer_type = ... # type: typing___Text
    extrinsic_reward_enabled = ... # type: builtin___bool
    gail_reward_enabled = ... # type: builtin___bool
    curiosity_reward_enabled = ... # type: builtin___bool
    rnd_reward_enabled = ... # type: builtin___bool
    behavioral_cloning_enabled = ... # type: builtin___bool
    recurrent_enabled = ... # type: builtin___bool
    visual_encoder = ... # type: typing___Text
    num_network_layers = ... # type: builtin___int
    num_network_hidden_units = ... # type: builtin___int
    trainer_threaded = ... # type: builtin___bool
    self_play_enabled = ... # type: builtin___bool
    curriculum_enabled = ... # type: builtin___bool
    config = ... # type: typing___Text

    def __init__(self,
        *,
        behavior_name : typing___Optional[typing___Text] = None,
        trainer_type : typing___Optional[typing___Text] = None,
        extrinsic_reward_enabled : typing___Optional[builtin___bool] = None,
        gail_reward_enabled : typing___Optional[builtin___bool] = None,
        curiosity_reward_enabled : typing___Optional[builtin___bool] = None,
        rnd_reward_enabled : typing___Optional[builtin___bool] = None,
        behavioral_cloning_enabled : typing___Optional[builtin___bool] = None,
        recurrent_enabled : typing___Optional[builtin___bool] = None,
        visual_encoder : typing___Optional[typing___Text] = None,
        num_network_layers : typing___Optional[builtin___int] = None,
        num_network_hidden_units : typing___Optional[builtin___int] = None,
        trainer_threaded : typing___Optional[builtin___bool] = None,
        self_play_enabled : typing___Optional[builtin___bool] = None,
        curriculum_enabled : typing___Optional[builtin___bool] = None,
        config : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> TrainingBehaviorInitialized: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"behavior_name",u"behavioral_cloning_enabled",u"config",u"curiosity_reward_enabled",u"curriculum_enabled",u"extrinsic_reward_enabled",u"gail_reward_enabled",u"num_network_hidden_units",u"num_network_layers",u"recurrent_enabled",u"rnd_reward_enabled",u"self_play_enabled",u"trainer_threaded",u"trainer_type",u"visual_encoder"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"behavior_name",b"behavior_name",u"behavioral_cloning_enabled",b"behavioral_cloning_enabled",u"config",b"config",u"curiosity_reward_enabled",b"curiosity_reward_enabled",u"curriculum_enabled",b"curriculum_enabled",u"extrinsic_reward_enabled",b"extrinsic_reward_enabled",u"gail_reward_enabled",b"gail_reward_enabled",u"num_network_hidden_units",b"num_network_hidden_units",u"num_network_layers",b"num_network_layers",u"recurrent_enabled",b"recurrent_enabled",u"rnd_reward_enabled",b"rnd_reward_enabled",u"self_play_enabled",b"self_play_enabled",u"trainer_threaded",b"trainer_threaded",u"trainer_type",b"trainer_type",u"visual_encoder",b"visual_encoder"]) -> None: ...
