"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import mlagents_envs.communicator_objects.header_pb2
import mlagents_envs.communicator_objects.unity_input_pb2
import mlagents_envs.communicator_objects.unity_output_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class UnityMessageProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    UNITY_OUTPUT_FIELD_NUMBER: builtins.int
    UNITY_INPUT_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> mlagents_envs.communicator_objects.header_pb2.HeaderProto: ...
    @property
    def unity_output(self) -> mlagents_envs.communicator_objects.unity_output_pb2.UnityOutputProto: ...
    @property
    def unity_input(self) -> mlagents_envs.communicator_objects.unity_input_pb2.UnityInputProto: ...
    def __init__(
        self,
        *,
        header: mlagents_envs.communicator_objects.header_pb2.HeaderProto | None = ...,
        unity_output: mlagents_envs.communicator_objects.unity_output_pb2.UnityOutputProto | None = ...,
        unity_input: mlagents_envs.communicator_objects.unity_input_pb2.UnityInputProto | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header", "unity_input", b"unity_input", "unity_output", b"unity_output"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["header", b"header", "unity_input", b"unity_input", "unity_output", b"unity_output"]) -> None: ...

global___UnityMessageProto = UnityMessageProto
