"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import mlagents_envs.communicator_objects.capabilities_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class UnityRLInitializationInputProto(google.protobuf.message.Message):
    """The initializaiton message - this is typically sent from the Python trainer to the C# environment."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEED_FIELD_NUMBER: builtins.int
    COMMUNICATION_VERSION_FIELD_NUMBER: builtins.int
    PACKAGE_VERSION_FIELD_NUMBER: builtins.int
    CAPABILITIES_FIELD_NUMBER: builtins.int
    NUM_AREAS_FIELD_NUMBER: builtins.int
    seed: builtins.int
    communication_version: builtins.str
    """Communication protocol version that the initiating side (typically the Python trainer) is using."""
    package_version: builtins.str
    """Package/library version that the initiating side (typically the Python trainer) is using."""
    @property
    def capabilities(self) -> mlagents_envs.communicator_objects.capabilities_pb2.UnityRLCapabilitiesProto:
        """The RL Capabilities of the Python trainer."""
    num_areas: builtins.int
    """The number of training areas to instantiate"""
    def __init__(
        self,
        *,
        seed: builtins.int = ...,
        communication_version: builtins.str = ...,
        package_version: builtins.str = ...,
        capabilities: mlagents_envs.communicator_objects.capabilities_pb2.UnityRLCapabilitiesProto | None = ...,
        num_areas: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["capabilities", b"capabilities"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["capabilities", b"capabilities", "communication_version", b"communication_version", "num_areas", b"num_areas", "package_version", b"package_version", "seed", b"seed"]) -> None: ...

global___UnityRLInitializationInputProto = UnityRLInitializationInputProto
