"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import mlagents_envs.communicator_objects.unity_rl_initialization_output_pb2
import mlagents_envs.communicator_objects.unity_rl_output_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class UnityOutputProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RL_OUTPUT_FIELD_NUMBER: builtins.int
    RL_INITIALIZATION_OUTPUT_FIELD_NUMBER: builtins.int
    @property
    def rl_output(self) -> mlagents_envs.communicator_objects.unity_rl_output_pb2.UnityRLOutputProto: ...
    @property
    def rl_initialization_output(self) -> mlagents_envs.communicator_objects.unity_rl_initialization_output_pb2.UnityRLInitializationOutputProto: ...
    def __init__(
        self,
        *,
        rl_output: mlagents_envs.communicator_objects.unity_rl_output_pb2.UnityRLOutputProto | None = ...,
        rl_initialization_output: mlagents_envs.communicator_objects.unity_rl_initialization_output_pb2.UnityRLInitializationOutputProto | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["rl_initialization_output", b"rl_initialization_output", "rl_output", b"rl_output"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["rl_initialization_output", b"rl_initialization_output", "rl_output", b"rl_output"]) -> None: ...

global___UnityOutputProto = UnityOutputProto
