import logging

from communicator_objects import UnityRLOutput, UnityRLInput,\
    UnityOutput, UnityInput, AcademyParameters,\
    UnityInitializationInput, UnityInitializationOutput

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("unityagents")


class Communicator(object):
    def __init__(self, worker_id=0,
                 base_port=5005):
        """
        Python side of the communication

        :int base_port: Baseline port number to connect to Unity environment over. worker_id increments over this.
        :int worker_id: Number to add to communication port (5005) [0]. Used for asynchronous agent scenarios.
        """

    def get_academy_parameters(self, python_parameters) -> AcademyParameters:
        """
        Used to exchange initialization parameters between Python and the Environment
        :param python_parameters: The python parameters that will be sent to the environment.
        :return: AcademyParameters: The parameters received from the environment
        """

    def send(self, inputs: UnityRLInput) -> UnityRLOutput:
        """
        Used to send an input and receive an output the Environment
        :param inputs: The UnityRLInput that needs to be sent the Environment
        :return: The UnityRLOutputs generated by the Environment
        """

    def close(self):
        """
        Sends a shutdown signal to the unity environment, and closes the connection.
        """
        # inputs = UnityInput()
        # inputs.command = 2
        # How to shut gRPC down ?
        try:
            message_input = UnityInput()
            message_input.header.status = 400
            self._communicator_send(message_input.SerializeToString())
        except :
            pass
        # if self._conn is not None:
        #     self._conn.send(b"EXIT")
        #     self._conn.close()
        #     self._socket.close()
        #     self._conn = None

