# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from mlagents.envs.communicator_objects.agent_info_proto_pb2 import (
    AgentInfoProto as mlagents___envs___communicator_objects___agent_info_proto_pb2___AgentInfoProto,
)

from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class UnityRLOutput(google___protobuf___message___Message):
    class ListAgentInfoProto(google___protobuf___message___Message):

        @property
        def value(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[mlagents___envs___communicator_objects___agent_info_proto_pb2___AgentInfoProto]: ...

        def __init__(self,
            value : typing___Optional[typing___Iterable[mlagents___envs___communicator_objects___agent_info_proto_pb2___AgentInfoProto]] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> UnityRLOutput.ListAgentInfoProto: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def ClearField(self, field_name: typing_extensions___Literal[u"value"]) -> None: ...
        else:
            def ClearField(self, field_name: typing_extensions___Literal[b"value"]) -> None: ...

    class AgentInfosEntry(google___protobuf___message___Message):
        key = ... # type: typing___Text

        @property
        def value(self) -> UnityRLOutput.ListAgentInfoProto: ...

        def __init__(self,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[UnityRLOutput.ListAgentInfoProto] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> UnityRLOutput.AgentInfosEntry: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def HasField(self, field_name: typing_extensions___Literal[u"value"]) -> bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"key",u"value"]) -> None: ...
        else:
            def HasField(self, field_name: typing_extensions___Literal[u"value",b"value"]) -> bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[b"key",b"value"]) -> None: ...

    global_done = ... # type: bool

    @property
    def agentInfos(self) -> typing___MutableMapping[typing___Text, UnityRLOutput.ListAgentInfoProto]: ...

    def __init__(self,
        global_done : typing___Optional[bool] = None,
        agentInfos : typing___Optional[typing___Mapping[typing___Text, UnityRLOutput.ListAgentInfoProto]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> UnityRLOutput: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"agentInfos",u"global_done"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"agentInfos",b"global_done"]) -> None: ...
