// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: communicator/unity_initialization_output.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MLAgents.Communicator {

  /// <summary>Holder for reflection information generated from communicator/unity_initialization_output.proto</summary>
  public static partial class UnityInitializationOutputReflection {

    #region Descriptor
    /// <summary>File descriptor for communicator/unity_initialization_output.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityInitializationOutputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5jb21tdW5pY2F0b3IvdW5pdHlfaW5pdGlhbGl6YXRpb25fb3V0cHV0LnBy",
            "b3RvEgxjb21tdW5pY2F0b3IaJWNvbW11bmljYXRvci9hY2FkZW15X3BhcmFt",
            "ZXRlcnMucHJvdG8aGWNvbW11bmljYXRvci9oZWFkZXIucHJvdG8ifgoZVW5p",
            "dHlJbml0aWFsaXphdGlvbk91dHB1dBIkCgZoZWFkZXIYASABKAsyFC5jb21t",
            "dW5pY2F0b3IuSGVhZGVyEjsKEmFjYWRlbXlfcGFyYW1ldGVycxgCIAEoCzIf",
            "LmNvbW11bmljYXRvci5BY2FkZW15UGFyYW1ldGVyc0IYqgIVTUxBZ2VudHMu",
            "Q29tbXVuaWNhdG9yYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MLAgents.Communicator.AcademyParametersReflection.Descriptor, global::MLAgents.Communicator.HeaderReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MLAgents.Communicator.UnityInitializationOutput), global::MLAgents.Communicator.UnityInitializationOutput.Parser, new[]{ "Header", "AcademyParameters" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UnityInitializationOutput : pb::IMessage<UnityInitializationOutput> {
    private static readonly pb::MessageParser<UnityInitializationOutput> _parser = new pb::MessageParser<UnityInitializationOutput>(() => new UnityInitializationOutput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityInitializationOutput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MLAgents.Communicator.UnityInitializationOutputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInitializationOutput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInitializationOutput(UnityInitializationOutput other) : this() {
      Header = other.header_ != null ? other.Header.Clone() : null;
      AcademyParameters = other.academyParameters_ != null ? other.AcademyParameters.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInitializationOutput Clone() {
      return new UnityInitializationOutput(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::MLAgents.Communicator.Header header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MLAgents.Communicator.Header Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "academy_parameters" field.</summary>
    public const int AcademyParametersFieldNumber = 2;
    private global::MLAgents.Communicator.AcademyParameters academyParameters_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MLAgents.Communicator.AcademyParameters AcademyParameters {
      get { return academyParameters_; }
      set {
        academyParameters_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityInitializationOutput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityInitializationOutput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (!object.Equals(AcademyParameters, other.AcademyParameters)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (academyParameters_ != null) hash ^= AcademyParameters.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (academyParameters_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AcademyParameters);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (academyParameters_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AcademyParameters);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityInitializationOutput other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          header_ = new global::MLAgents.Communicator.Header();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.academyParameters_ != null) {
        if (academyParameters_ == null) {
          academyParameters_ = new global::MLAgents.Communicator.AcademyParameters();
        }
        AcademyParameters.MergeFrom(other.AcademyParameters);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              header_ = new global::MLAgents.Communicator.Header();
            }
            input.ReadMessage(header_);
            break;
          }
          case 18: {
            if (academyParameters_ == null) {
              academyParameters_ = new global::MLAgents.Communicator.AcademyParameters();
            }
            input.ReadMessage(academyParameters_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
