// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: communicator/unity_rl_output.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MLAgents.Communicator {

  /// <summary>Holder for reflection information generated from communicator/unity_rl_output.proto</summary>
  public static partial class UnityRlOutputReflection {

    #region Descriptor
    /// <summary>File descriptor for communicator/unity_rl_output.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityRlOutputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJjb21tdW5pY2F0b3IvdW5pdHlfcmxfb3V0cHV0LnByb3RvEgxjb21tdW5p",
            "Y2F0b3IaHWNvbW11bmljYXRvci9hZ2VudF9pbmZvLnByb3RvIvwBCg1Vbml0",
            "eVJMT3V0cHV0EhMKC2dsb2JhbF9kb25lGAEgASgIEj8KCmFnZW50SW5mb3MY",
            "AiADKAsyKy5jb21tdW5pY2F0b3IuVW5pdHlSTE91dHB1dC5BZ2VudEluZm9z",
            "RW50cnkaNwoNTGlzdEFnZW50SW5mbxImCgV2YWx1ZRgBIAMoCzIXLmNvbW11",
            "bmljYXRvci5BZ2VudEluZm8aXAoPQWdlbnRJbmZvc0VudHJ5EgsKA2tleRgB",
            "IAEoCRI4CgV2YWx1ZRgCIAEoCzIpLmNvbW11bmljYXRvci5Vbml0eVJMT3V0",
            "cHV0Lkxpc3RBZ2VudEluZm86AjgBQhiqAhVNTEFnZW50cy5Db21tdW5pY2F0",
            "b3JiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MLAgents.Communicator.AgentInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MLAgents.Communicator.UnityRLOutput), global::MLAgents.Communicator.UnityRLOutput.Parser, new[]{ "GlobalDone", "AgentInfos" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::MLAgents.Communicator.UnityRLOutput.Types.ListAgentInfo), global::MLAgents.Communicator.UnityRLOutput.Types.ListAgentInfo.Parser, new[]{ "Value" }, null, null, null),
            null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UnityRLOutput : pb::IMessage<UnityRLOutput> {
    private static readonly pb::MessageParser<UnityRLOutput> _parser = new pb::MessageParser<UnityRLOutput>(() => new UnityRLOutput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityRLOutput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MLAgents.Communicator.UnityRlOutputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityRLOutput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityRLOutput(UnityRLOutput other) : this() {
      globalDone_ = other.globalDone_;
      agentInfos_ = other.agentInfos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityRLOutput Clone() {
      return new UnityRLOutput(this);
    }

    /// <summary>Field number for the "global_done" field.</summary>
    public const int GlobalDoneFieldNumber = 1;
    private bool globalDone_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool GlobalDone {
      get { return globalDone_; }
      set {
        globalDone_ = value;
      }
    }

    /// <summary>Field number for the "agentInfos" field.</summary>
    public const int AgentInfosFieldNumber = 2;
    private static readonly pbc::MapField<string, global::MLAgents.Communicator.UnityRLOutput.Types.ListAgentInfo>.Codec _map_agentInfos_codec
        = new pbc::MapField<string, global::MLAgents.Communicator.UnityRLOutput.Types.ListAgentInfo>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::MLAgents.Communicator.UnityRLOutput.Types.ListAgentInfo.Parser), 18);
    private readonly pbc::MapField<string, global::MLAgents.Communicator.UnityRLOutput.Types.ListAgentInfo> agentInfos_ = new pbc::MapField<string, global::MLAgents.Communicator.UnityRLOutput.Types.ListAgentInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::MLAgents.Communicator.UnityRLOutput.Types.ListAgentInfo> AgentInfos {
      get { return agentInfos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityRLOutput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityRLOutput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GlobalDone != other.GlobalDone) return false;
      if (!AgentInfos.Equals(other.AgentInfos)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GlobalDone != false) hash ^= GlobalDone.GetHashCode();
      hash ^= AgentInfos.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GlobalDone != false) {
        output.WriteRawTag(8);
        output.WriteBool(GlobalDone);
      }
      agentInfos_.WriteTo(output, _map_agentInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GlobalDone != false) {
        size += 1 + 1;
      }
      size += agentInfos_.CalculateSize(_map_agentInfos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityRLOutput other) {
      if (other == null) {
        return;
      }
      if (other.GlobalDone != false) {
        GlobalDone = other.GlobalDone;
      }
      agentInfos_.Add(other.agentInfos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GlobalDone = input.ReadBool();
            break;
          }
          case 18: {
            agentInfos_.AddEntriesFrom(input, _map_agentInfos_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the UnityRLOutput message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class ListAgentInfo : pb::IMessage<ListAgentInfo> {
        private static readonly pb::MessageParser<ListAgentInfo> _parser = new pb::MessageParser<ListAgentInfo>(() => new ListAgentInfo());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<ListAgentInfo> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::MLAgents.Communicator.UnityRLOutput.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ListAgentInfo() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ListAgentInfo(ListAgentInfo other) : this() {
          value_ = other.value_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ListAgentInfo Clone() {
          return new ListAgentInfo(this);
        }

        /// <summary>Field number for the "value" field.</summary>
        public const int ValueFieldNumber = 1;
        private static readonly pb::FieldCodec<global::MLAgents.Communicator.AgentInfo> _repeated_value_codec
            = pb::FieldCodec.ForMessage(10, global::MLAgents.Communicator.AgentInfo.Parser);
        private readonly pbc::RepeatedField<global::MLAgents.Communicator.AgentInfo> value_ = new pbc::RepeatedField<global::MLAgents.Communicator.AgentInfo>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::MLAgents.Communicator.AgentInfo> Value {
          get { return value_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as ListAgentInfo);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(ListAgentInfo other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!value_.Equals(other.value_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= value_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          value_.WriteTo(output, _repeated_value_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          size += value_.CalculateSize(_repeated_value_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(ListAgentInfo other) {
          if (other == null) {
            return;
          }
          value_.Add(other.value_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                value_.AddEntriesFrom(input, _repeated_value_codec);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
