{% metadata_file .yamato/test_versions.metafile %}
---
{% for editor in test_editors %}
test_mac_training_int_{{ editor.version }}:
  name: Test Mac Fast Training {{ editor.version }}
  agent:
    type: Unity::VM::osx
    image: ml-agents/ml-agents-bokken-mac:0.1.4-492264
    flavor: b1.small
  variables:
    UNITY_VERSION: {{ editor.version }}
  commands:
    - pip install pyyaml --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple
    # TODO remove the "--user" command and the path prefix when we can migrate away from the custom bokken image
    - python -m pip install unity-downloader-cli --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple --upgrade --user
    - /Users/bokken/Library/Python/3.7/bin/unity-downloader-cli -u {{ editor.version }} -c editor --wait --fast
    - python -u -m ml-agents.tests.yamato.training_int_tests
    # Backwards-compatibility tests.
    # If we make a breaking change to the communication protocol, these will need
    # to be disabled until the next release.
    - python -u -m ml-agents.tests.yamato.training_int_tests --python=0.16.0
    - python -u -m ml-agents.tests.yamato.training_int_tests --csharp={{ editor.csharp_backcompat_version }}
  dependencies:
    - .yamato/standalone-build-test.yml#test_mac_standalone_{{ editor.version }}
  triggers:
    cancel_old_ci: true
    expression: |
      (pull_request.target eq "master" OR
      pull_request.target match "release.+") AND
      NOT pull_request.draft AND
      (pull_request.changes.any match "com.unity.ml-agents/**" OR
      pull_request.changes.any match "com.unity.ml-agents.extensions/**" OR
      pull_request.changes.any match "Project/**" OR
      pull_request.changes.any match "ml-agents/**" OR
      pull_request.changes.any match "ml-agents-envs/**" OR
      pull_request.changes.any match ".yamato/training-int-tests.yml") AND
      NOT pull_request.changes.all match "**/*.md"
  artifacts:
    logs:
      paths:
        - "artifacts/standalone_build.txt"
        - "artifacts/inference.nn.txt"
        - "artifacts/inference.onnx.txt"
    standalonebuild:
      paths:
        - "artifacts/testplayer*/**"
        - "artifacts/models/**"
{% endfor %}
