test_editors:
  - version: 2018.4
  - version: 2019.3
---
{% for editor in test_editors %}
test_mac_training_int_{{ editor.version }}:
  name: Test Mac Fast Training {{ editor.version }}
  agent:
    type: Unity::VM::osx
    image: ml-agents/ml-agents-bokken-mac:0.1.4-492264
    flavor: b1.small
  variables:
    UNITY_VERSION: {{ editor.version }}
  commands:
    - pip install pyyaml
    - python -u -m ml-agents.tests.yamato.training_int_tests
  triggers:
    cancel_old_ci: true
    changes:
      only:
        - "com.unity.ml-agents/**"
        - "Project/**"
        - "ml-agents/**"
        - "ml-agents-envs/**"
        - ".yamato/training-int-tests.yml"
      except:
        - "*.md"
        - "com.unity.ml-agents/*.md"
        - "com.unity.ml-agents/**/*.md"
  artifacts:
    unit:
      paths:
        - "artifacts/**"
{% endfor %}
