import logging
import os

import argparse

import yaml
import json

import shutil

from pathlib import Path

from huggingface_hub import HfApi, HfFolder, Repository, upload_folder
from huggingface_hub.repocard import metadata_eval_result, metadata_save

from typing import Optional


def _generate_config(repo_local_path, configfile_name):
    """
    Generate a config.json file from configuration.yaml
    To do that we convert yaml to json
    :param repo_local_path: path of the local repository
    :param configfile_name: name of the yaml config file (by default configuration.yaml)
    """
    # Read the YAML file and generate a config.json
    with open(os.path.join(repo_local_path, configfile_name), "r") as yaml_in, open(
        os.path.join(repo_local_path, "config.json"), "w") as json_out:
        yaml_object = yaml.safe_load(yaml_in)
        json.dump(yaml_object, json_out)


def _generate_metadata(model_name: str, env_id: str, mean_reward: float, std_reward: float):
    """
    Define the tags for the model card
    :param model_name: name of the model
    :param env_id: name of the environment
    :mean_reward: mean reward of the agent
    :std_reward: standard deviation of the mean reward of the agent
    """
    env_tag = "ML-Agents-" + env_id

    metadata = {}
    metadata["library_name"] = "ml-agents"
    metadata["tags"] = [
        env_id,
        "deep-reinforcement-learning",
        "reinforcement-learning",
        env_tag,
    ]

    """
    TODO: Need to get the evaluation metrics
    # Add metrics
    eval = metadata_eval_result(
        model_pretty_name=model_name,
        task_pretty_name="reinforcement-learning",
        task_id="reinforcement-learning",
        metrics_pretty_name="mean_reward",
        metrics_id="mean_reward",
        metrics_value=f"{mean_reward:.2f} +/- {std_reward:.2f}",
        dataset_pretty_name=env_id,
        dataset_id=env_id,
    )
    
    # Merges both dictionaries
    metadata = {**metadata, **eval}
    """

    return metadata


def _generate_model_card(repo_local_path, configfile_name, repo_id):
    """
    Generate the model card for the Hub
    :param model_name: name of the model
    :env_id: name of the environment
    :mean_reward: mean reward of the agent
    :std_reward: standard deviation of the mean reward of the agent
    """
    # Step 1: Read the config.json
    with open(os.path.join(repo_local_path, "config.json"), 'r') as f:
        data = json.load(f)
        # Get env_id
        env_id = list(data["behaviors"].keys())[0]
        # Get trainer_type
        model_name = data["behaviors"][env_id]["trainer_type"]

    # Step 2: Create the metadata
    metadata = _generate_metadata(model_name, env_id)

    # Step 3: Generate the model card
    model_card = f"""
  # **{model_name}** Agent playing **{env_id}**
  This is a trained model of a **{model_name}** agent playing **{env_id}** using the [Unity ML-Agents Library](https://github.com/Unity-Technologies/ml-agents).
  """

    model_card += """
  ## Usage (with ML-Agents)
  The Documentation: https://github.com/huggingface/ml-agents#get-started
  We wrote a complete tutorial to learn to train your first agent using ML-Agents and publish it to the Hub:


  ### Resume the training
  ```
  mlagents-learn <your_configuration_file_path.yaml> --run-id=<run_id> --resume
  ```
  ### Watch your Agent play
  You can watch your agent **playing directly in your browser:**.
  """

    model_card += f"""
  1. Go to https://huggingface.co/spaces/unity/ML-Agents-{env_id}
  2. Step 1: Find your model_id: {repo_id}
  3. Step 2: Select your *.nn /*.onnx file
  4. Click on Watch the agent play 👀
  """

    return model_card, metadata


def _save_model_card(repo_dir: Path, generated_model_card: str, metadata):
    """Save a model card to the repository.
    :param repo_dir: repository directory
    :param generated_model_card: model card generated by _generate_model_card() method
    :param metadata: metadata
    """
    readme_path = repo_dir / "README.md"
    readme = ""
    if readme_path.exists():
        with readme_path.open("r", encoding="utf8") as f:
            readme = f.read()
    else:
        readme = generated_model_card
    with readme_path.open("w", encoding="utf-8") as f:
        f.write(readme)

    # Save our metrics to Readme metadata
    metadata_save(readme_path, metadata)


def package_to_hub(run_id,
                   path_of_run_id,
                   repo_id: str,
                   commit_message: str,
                   configfile_name,
                   token: Optional[str] = None,
                   local_repo_path="hub",
                   ):
    """
    This method generates the model card and upload the run_id folder
    with all his files into the Hub
    :param run_id : name of the run
    :param path_of_run_id: path of the run_id folder that contains the onnx model.
    :param commit_message: commit message
    :param configfile_name: name of the yaml config file (by default configuration.yaml)
    """
    logging.info(
        f"This function will create a model card and upload your {run_id} "
        f"into HuggingFace Hub. This is a work in progress: If you encounter a bug, "
        f"please send open an issue")

    _, repo_name = repo_id.split('/')

    # Step 1: Clone or create the repo
    # Create the repo (or clone its content if it's nonempty)
    api = HfApi()
    repo_url = api.create_repo(
        repo_id=repo_id,
        exist_ok=True, )

    # Step 2: Download the files
    # Git pull
    repo_local_path = Path(local_repo_path) / repo_name
    repo = Repository(repo_local_path, clone_from=repo_url, use_auth_token=use_auth_token)
    repo.git_pull(rebase=True)
    repo.lfs_track(["*.onnx"])

    # Step 3: Copy and paste the files to the repo
    repo_local_path = Path(local_repo_path) / repo_name

    # Store the source and destination directory path into two variables
    src_path = Path(path_of_run_id)
    dst_path = repo_local_path

    for filename in src_path.iterdir():
        _copy_file(Path(filename), repo_local_path)

    # Step 4: Create a config file
    _generate_config(repo_local_path, configfile_name)

    # Step 5: Generate and save the model card
    generated_model_card, metadata = _generate_model_card(repo_local_path, configfile_name, repo_id)
    _save_model_card(repo_local_path, generated_model_card, metadata)

    logging.info(f"Pushing repo {run_id} to the Hugging Face Hub")
    repo.push_to_hub(commit_message=commit_message)

    logging.info(f"Your model is pushed to the hub. You can view your model here: {repo_url}")
    print(f"\n Your model is pushed to the hub. You can view your model here: {repo_url}")
    return repo_url


def _copy_file(filepath: Path, dst_directory: Path):
    """
    Copy the file to the correct directory
    :param filepath: path of the file
    :param dst_directory: destination directory
    """
    dst = dst_directory / filepath.name

    if dst.is_dir():
        shutil.rmtree(str(dst))
    elif dst.is_file():
        dst.unlink()
    if filepath.is_dir():
        shutil.copytree(filepath, dst)
    elif filepath.is_file():
        shutil.copy(str(filepath), str(dst))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-id", help="Name of the run-id folder", type=str)
    parser.add_argument("--local-dir", help="Path of the run_id folder that contains the trained model", type=str, default="./")
    parser.add_argument("--repo-id", help="Repo id of the model repository from the Hugging Face Hub", type=str)
    parser.add_argument("--commit-message", help="Commit message", type=str)
    parser.add_argument("--configfile-name", help="Name of the configuration yaml file", type=str,
                        default="configuration.yaml")
    parser.add_argument("--use_auth_token", type=bool, default=True)
    parser.add_argument("--local-repo-path", help="local repository path", type=str, default="hub")
    args = parser.parse_args()

    # Push model to hub
    package_to_hub(args.run_id,
                   args.local_dir,
                   args.repo_id,
                   args.commit_message,
                   args.configfile_name,
                   args.use_auth_token,
                   args.local_repo_path)

# For python debugger to directly run this script
if __name__ == "__main__":
    main()

