# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communicator/communicator_parameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communicator/communicator_parameters.proto',
  package='communicator',
  syntax='proto3',
  serialized_pb=_b('\n*communicator/communicator_parameters.proto\x12\x0c\x63ommunicator\"&\n\x16\x43ommunicatorParameters\x12\x0c\n\x04port\x18\x01 \x01(\x05\x42\x18\xaa\x02\x15MLAgents.Communicatorb\x06proto3')
)




_COMMUNICATORPARAMETERS = _descriptor.Descriptor(
  name='CommunicatorParameters',
  full_name='communicator.CommunicatorParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='communicator.CommunicatorParameters.port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['CommunicatorParameters'] = _COMMUNICATORPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommunicatorParameters = _reflection.GeneratedProtocolMessageType('CommunicatorParameters', (_message.Message,), dict(
  DESCRIPTOR = _COMMUNICATORPARAMETERS,
  __module__ = 'communicator.communicator_parameters_pb2'
  # @@protoc_insertion_point(class_scope:communicator.CommunicatorParameters)
  ))
_sym_db.RegisterMessage(CommunicatorParameters)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\025MLAgents.Communicator'))
# @@protoc_insertion_point(module_scope)
