# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communicator/environment_parameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communicator/environment_parameters.proto',
  package='communicator',
  syntax='proto3',
  serialized_pb=_b('\n)communicator/environment_parameters.proto\x12\x0c\x63ommunicator\"\xa3\x01\n\x15\x45nvironmentParameters\x12R\n\x10\x66loat_parameters\x18\x01 \x03(\x0b\x32\x38.communicator.EnvironmentParameters.FloatParametersEntry\x1a\x36\n\x14\x46loatParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x42\x18\xaa\x02\x15MLAgents.Communicatorb\x06proto3')
)




_ENVIRONMENTPARAMETERS_FLOATPARAMETERSENTRY = _descriptor.Descriptor(
  name='FloatParametersEntry',
  full_name='communicator.EnvironmentParameters.FloatParametersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='communicator.EnvironmentParameters.FloatParametersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='communicator.EnvironmentParameters.FloatParametersEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=223,
)

_ENVIRONMENTPARAMETERS = _descriptor.Descriptor(
  name='EnvironmentParameters',
  full_name='communicator.EnvironmentParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='float_parameters', full_name='communicator.EnvironmentParameters.float_parameters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ENVIRONMENTPARAMETERS_FLOATPARAMETERSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=223,
)

_ENVIRONMENTPARAMETERS_FLOATPARAMETERSENTRY.containing_type = _ENVIRONMENTPARAMETERS
_ENVIRONMENTPARAMETERS.fields_by_name['float_parameters'].message_type = _ENVIRONMENTPARAMETERS_FLOATPARAMETERSENTRY
DESCRIPTOR.message_types_by_name['EnvironmentParameters'] = _ENVIRONMENTPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnvironmentParameters = _reflection.GeneratedProtocolMessageType('EnvironmentParameters', (_message.Message,), dict(

  FloatParametersEntry = _reflection.GeneratedProtocolMessageType('FloatParametersEntry', (_message.Message,), dict(
    DESCRIPTOR = _ENVIRONMENTPARAMETERS_FLOATPARAMETERSENTRY,
    __module__ = 'communicator.environment_parameters_pb2'
    # @@protoc_insertion_point(class_scope:communicator.EnvironmentParameters.FloatParametersEntry)
    ))
  ,
  DESCRIPTOR = _ENVIRONMENTPARAMETERS,
  __module__ = 'communicator.environment_parameters_pb2'
  # @@protoc_insertion_point(class_scope:communicator.EnvironmentParameters)
  ))
_sym_db.RegisterMessage(EnvironmentParameters)
_sym_db.RegisterMessage(EnvironmentParameters.FloatParametersEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\025MLAgents.Communicator'))
_ENVIRONMENTPARAMETERS_FLOATPARAMETERSENTRY.has_options = True
_ENVIRONMENTPARAMETERS_FLOATPARAMETERSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
