# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communicator/python_parameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communicator/python_parameters.proto',
  package='communicator',
  syntax='proto3',
  serialized_pb=_b('\n$communicator/python_parameters.proto\x12\x0c\x63ommunicator\" \n\x10PythonParameters\x12\x0c\n\x04seed\x18\x01 \x01(\x05\x42\x18\xaa\x02\x15MLAgents.Communicatorb\x06proto3')
)




_PYTHONPARAMETERS = _descriptor.Descriptor(
  name='PythonParameters',
  full_name='communicator.PythonParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seed', full_name='communicator.PythonParameters.seed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['PythonParameters'] = _PYTHONPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PythonParameters = _reflection.GeneratedProtocolMessageType('PythonParameters', (_message.Message,), dict(
  DESCRIPTOR = _PYTHONPARAMETERS,
  __module__ = 'communicator.python_parameters_pb2'
  # @@protoc_insertion_point(class_scope:communicator.PythonParameters)
  ))
_sym_db.RegisterMessage(PythonParameters)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\025MLAgents.Communicator'))
# @@protoc_insertion_point(module_scope)
