# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communicator/unity_output.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from communicator import unity_rl_output_pb2 as communicator_dot_unity__rl__output__pb2
from communicator import header_pb2 as communicator_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='communicator/unity_output.proto',
  package='communicator',
  syntax='proto3',
  serialized_pb=_b('\n\x1f\x63ommunicator/unity_output.proto\x12\x0c\x63ommunicator\x1a\"communicator/unity_rl_output.proto\x1a\x19\x63ommunicator/header.proto\"c\n\x0bUnityOutput\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.communicator.Header\x12.\n\trl_output\x18\x02 \x01(\x0b\x32\x1b.communicator.UnityRLOutputB\x18\xaa\x02\x15MLAgents.Communicatorb\x06proto3')
  ,
  dependencies=[communicator_dot_unity__rl__output__pb2.DESCRIPTOR,communicator_dot_header__pb2.DESCRIPTOR,])




_UNITYOUTPUT = _descriptor.Descriptor(
  name='UnityOutput',
  full_name='communicator.UnityOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='communicator.UnityOutput.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rl_output', full_name='communicator.UnityOutput.rl_output', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=211,
)

_UNITYOUTPUT.fields_by_name['header'].message_type = communicator_dot_header__pb2._HEADER
_UNITYOUTPUT.fields_by_name['rl_output'].message_type = communicator_dot_unity__rl__output__pb2._UNITYRLOUTPUT
DESCRIPTOR.message_types_by_name['UnityOutput'] = _UNITYOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnityOutput = _reflection.GeneratedProtocolMessageType('UnityOutput', (_message.Message,), dict(
  DESCRIPTOR = _UNITYOUTPUT,
  __module__ = 'communicator.unity_output_pb2'
  # @@protoc_insertion_point(class_scope:communicator.UnityOutput)
  ))
_sym_db.RegisterMessage(UnityOutput)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\025MLAgents.Communicator'))
# @@protoc_insertion_point(module_scope)
