# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communicator/visual_observation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communicator/visual_observation.proto',
  package='communicator',
  syntax='proto3',
  serialized_pb=_b('\n%communicator/visual_observation.proto\x12\x0c\x63ommunicator\"U\n\x11VisualObservation\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x12\n\ngray_scale\x18\x03 \x01(\x08\x12\r\n\x05value\x18\x04 \x03(\x05\x42\x18\xaa\x02\x15MLAgents.Communicatorb\x06proto3')
)




_VISUALOBSERVATION = _descriptor.Descriptor(
  name='VisualObservation',
  full_name='communicator.VisualObservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='communicator.VisualObservation.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='communicator.VisualObservation.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gray_scale', full_name='communicator.VisualObservation.gray_scale', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='communicator.VisualObservation.value', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['VisualObservation'] = _VISUALOBSERVATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VisualObservation = _reflection.GeneratedProtocolMessageType('VisualObservation', (_message.Message,), dict(
  DESCRIPTOR = _VISUALOBSERVATION,
  __module__ = 'communicator.visual_observation_pb2'
  # @@protoc_insertion_point(class_scope:communicator.VisualObservation)
  ))
_sym_db.RegisterMessage(VisualObservation)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\025MLAgents.Communicator'))
# @@protoc_insertion_point(module_scope)
